AWSTemplateFormatVersion: 2010-09-09

Parameters:
  # Common Availability Zone

  AvailabilityZones:
    Type: String
    Default: us-east-1a
    Description: The Region to use. Default Region is us-east-1a.

  # For Ec2 Instance

  # InstanceTypeParameter:
  #   Type: String
  #   Default: t2.micro
  #   Description: Enter instance size. Default is t2.micro.

  # AMI:
  #   Type: String
  #   Default: ami-0892d3c7ee96c0bf7
  #   Description: The Linux AMI to use. Default is Ubuntu.

Resources:
  # For Backend

  # NodeJSBackend:
  #   Type: AWS::EC2::Instance
  #   Properties:
  #     ImageId: !Ref AMI
  #     InstanceType: !Ref InstanceTypeParameter
  #     KeyName: foodatrescue
  #     SecurityGroupIds:
  #       - !Ref EC2BackendSecurityGroup

  # EC2BackendSecurityGroup:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties:
  #     GroupName: NodeJS Backend Security Group
  #     GroupDescription: "Allow HTTP/HTTPS and SSH inbound and outbound traffic"
  #     SecurityGroupIngress:
  #       - IpProtocol: tcp
  #         FromPort: 80
  #         ToPort: 80
  #         CidrIp: 0.0.0.0/0
  #       - IpProtocol: tcp
  #         FromPort: 443
  #         ToPort: 443
  #         CidrIp: 0.0.0.0/0
  #       - IpProtocol: tcp
  #         FromPort: 22
  #         ToPort: 22
  #         CidrIp: 0.0.0.0/0
  #       - IpProtocol: tcp
  #         FromPort: 8080
  #         ToPort: 8080
  #         CidrIp: 0.0.0.0/0

  # For Dynamo DB

  # FoodTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: Food1
  #     AttributeDefinitions:
  #       - AttributeName: "id"
  #         AttributeType: "S"
  #     KeySchema:
  #       - AttributeName: "id"
  #         KeyType: "HASH"
  #     TimeToLiveSpecification:
  #       AttributeName: "ExpirationTime"
  #       Enabled: true
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: "5"
  #       WriteCapacityUnits: "5"
  #   DependsOn:
  #     - DynamoDBUser

  # ReservationTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: Reservation1
  #     AttributeDefinitions:
  #       - AttributeName: "id"
  #         AttributeType: "S"
  #     KeySchema:
  #       - AttributeName: "id"
  #         KeyType: "HASH"
  #     TimeToLiveSpecification:
  #       AttributeName: "ExpirationTime"
  #       Enabled: true
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: "5"
  #       WriteCapacityUnits: "5"
  #   DependsOn:
  #     - DynamoDBUser

  # DynamoDBUser:
  #   Type: AWS::IAM::User
  #   Properties:
  #     UserName: DynamoDBUser
  #     ManagedPolicyArns:
  #       - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
  # DynamoDBUserAccessKey:
  #   Type: AWS::IAM::AccessKey
  #   Properties:
  #     UserName: !Ref DynamoDBUser

  # For S3 Bucket
  # FoodAtRescueS3Bucket:
  #   Type: AWS::S3::Bucket
  #   Description: Creating Amazon S3 bucket For Storage
  #   Properties:
  #     BucketName: foodatrescueclient
  #     AccessControl: PublicReadWrite
  #     PublicAccessBlockConfiguration:
  #       BlockPublicAcls: false
  #       BlockPublicPolicy: false
  #       IgnorePublicAcls: false
  #       RestrictPublicBuckets: false

  #   DependsOn:
  #     - S3User

  # S3User:
  #   Type: AWS::IAM::User
  #   Properties:
  #     UserName: S3User
  #     ManagedPolicyArns:
  #       - arn:aws:iam::aws:policy/AmazonS3FullAccess
  # S3UserUserAccessKey:
  #   Type: AWS::IAM::AccessKey
  #   Properties:
  #     UserName: !Ref S3User

Outputs:
  # InstanceId:
  #   Description: Instance Id of EC2 Instance
  #   Value: !Ref NodeJSBackend
  # PublicDNS:
  #   Description: Public DNS of the EC2 Instance
  #   Value: !GetAtt
  #     - NodeJSBackend
  #     - PublicDnsName
  # PublicIP:
  #   Description: Public IP of the EC2 Instance
  #   Value: !GetAtt
  #     - NodeJSBackend
  #     - PublicIp

  # DynamoDBAccessKeyID:
  #   Description: DynamoDb Access Key
  #   Value: !Ref DynamoDBUserAccessKey
  # DynamoDBSecretAccessKey:
  #   Description: DynamoDb Secret Access Key
  #   Value: !GetAtt DynamoDBUserAccessKey.SecretAccessKey
  # DynamoDBUser:
  #   Description: DynamoDb User Name
  #   Value: !Ref DynamoDBUser

  # S3Bucket:
  #   Description: S3 Bucket Name.
  #   Value: !Ref FoodAtRescueS3Bucket
  # S3AccessKeyID:
  #   Description: S3 Access Key
  #   Value: !Ref S3UserUserAccessKey
  # S3SecretAccessKey:
  #   Description: S3 Secret Access Key
  #   Value: !GetAtt S3UserUserAccessKey.SecretAccessKey
  # S3User:
  #   Description: DynamoDb User Name
  #   Value: !Ref S3User
